# setup-cims-tunnel.ps1
# One-shot Cloudflare Tunnel setup for the Stelarith CIMS multi-tenant server.
# ASCII-only on purpose: PowerShell 5.1 mis-parses non-BOM non-ASCII files.
#
# Prereq (interactive, cannot be automated):
#     cloudflared tunnel login        <-- authorizes the zone in a browser
#
# Usage:
#     powershell -ExecutionPolicy Bypass -File setup-cims-tunnel.ps1
#     powershell -ExecutionPolicy Bypass -File setup-cims-tunnel.ps1 -RegisterTask
#
# What it does:
#   1. verify cert.pem exists (i.e. tunnel login was completed)
#   2. create tunnel if missing (idempotent)
#   3. route DNS: <PanelHost>.<Zone> and *.<Zone>
#   4. write ~/.cloudflared/config.yml  (panel rule BEFORE wildcard rule)
#   5. validate the ingress config
#   6. optionally register a startup scheduled task

param(
    [string]$Zone       = "245959623.xyz",
    [string]$TunnelName = "stelarith-cims",
    [string]$PanelHost  = "panel",
    [int]$PanelPort     = 8090,
    [int]$ClientPort    = 8096,
    [switch]$RegisterTask,
    [switch]$WhatIfOnly
)

$ErrorActionPreference = "Stop"

function Info($m) { Write-Host "[*] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[OK] $m" -ForegroundColor Green }
function Warn($m) { Write-Host "[!] $m" -ForegroundColor Yellow }
function Die($m)  { Write-Host "[X] $m" -ForegroundColor Red; exit 1 }

# ---------------------------------------------------------------- 0. locate cloudflared
$cf = Join-Path $env:ProgramFiles "cloudflared\cloudflared.exe"
if (-not (Test-Path $cf)) { $cf = "C:\Program Files (x86)\cloudflared\cloudflared.exe" }
if (-not (Test-Path $cf)) {
    $c = Get-Command cloudflared -ErrorAction SilentlyContinue
    if ($c) { $cf = $c.Source } else { Die "cloudflared.exe not found" }
}
Info ("cloudflared = " + $cf)
& $cf --version 2>&1 | Select-Object -First 1 | ForEach-Object { Info $_ }

$cfDir  = Join-Path $env:USERPROFILE ".cloudflared"
$cert   = Join-Path $cfDir "cert.pem"
if (-not (Test-Path $cert)) {
    Die "Missing $cert  ->  run 'cloudflared tunnel login' first and finish the browser authorization."
}
Ok "cert.pem found (zone authorization completed)"

# ---------------------------------------------------------------- 1. tunnel create (idempotent)
$tunnels = @()
try {
    $json = & $cf tunnel list --output json 2>$null
    if ($json) { $tunnels = $json | ConvertFrom-Json }
} catch { }

$tunnel = $tunnels | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1

if (-not $tunnel) {
    if ($WhatIfOnly) { Info "[dry] would create tunnel '$TunnelName'" }
    else {
        Info "Creating tunnel '$TunnelName' ..."
        & $cf tunnel create $TunnelName
        if ($LASTEXITCODE -ne 0) { Die "tunnel create failed" }
        $json = & $cf tunnel list --output json 2>$null
        $tunnel = ($json | ConvertFrom-Json) | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1
        if (-not $tunnel) { Die "tunnel created but not found in list" }
    }
}
if ($tunnel) { Ok ("tunnel id = " + $tunnel.id + "  name = " + $tunnel.name) }

$tunnelId  = $tunnel.id
$credFile  = Join-Path $cfDir "$tunnelId.json"
if (-not $WhatIfOnly -and -not (Test-Path $credFile)) { Die "credentials file missing: $credFile" }

# ---------------------------------------------------------------- 2. DNS routes
$panelFqdn = "$PanelHost.$Zone"
$wildFqdn  = "*.$Zone"

foreach ($fqdn in @($panelFqdn, $wildFqdn)) {
    if ($WhatIfOnly) { Info "[dry] would route DNS $fqdn -> tunnel" ; continue }
    Info "Routing DNS: $fqdn"
    & $cf tunnel route dns $tunnelId $fqdn 2>&1 | ForEach-Object { "      $_" }
    # exit code 1 usually means "record already exists" -- not fatal
}

# ---------------------------------------------------------------- 3. config.yml
$cfgPath = Join-Path $cfDir "config.yml"
$credYaml = $credFile.Replace("\", "/")

$yaml = @"
# Generated by setup-cims-tunnel.ps1 -- keep the SAME file on every server instance.
tunnel: $tunnelId
credentials-file: $credYaml

ingress:
  # Panel MUST come before the wildcard rule, otherwise it is swallowed by it.
  # Served by the website (SvelteKit) on $PanelPort.
  - hostname: $panelFqdn
    service: http://127.0.0.1:$PanelPort

  # Client API for every tenant: one rule covers all schools/classes.
  # NOTE: do NOT set originRequest.httpHostHeader -- the tenant middleware
  #       needs the client Host header forwarded verbatim.
  - hostname: "$wildFqdn"
    service: http://127.0.0.1:$ClientPort

  # Required catch-all.
  - service: http_status:404
"@

if ($WhatIfOnly) {
    Info "[dry] would write $cfgPath"
    Write-Host $yaml
} else {
    if (Test-Path $cfgPath) {
        $bak = "$cfgPath.bak-" + (Get-Date -Format yyyyMMdd-HHmmss)
        Copy-Item $cfgPath $bak
        Warn "existing config.yml backed up -> $bak"
    }
    # UTF-8 without BOM (cloudflared tolerates BOM but plain is safer)
    [System.IO.File]::WriteAllText($cfgPath, $yaml, (New-Object System.Text.UTF8Encoding($false)))
    Ok "wrote $cfgPath"
}

# ---------------------------------------------------------------- 4. validate
if (-not $WhatIfOnly) {
    Info "Validating ingress rules ..."
    & $cf tunnel ingress validate 2>&1 | ForEach-Object { "      $_" }
    Write-Host ""
    Info "Resolved ingress table:"
    & $cf tunnel ingress rule "https://$panelFqdn/x" 2>&1 | ForEach-Object { "      $_" }
    & $cf tunnel ingress rule "https://demo-class.$Zone/api/v1/client/manifest" 2>&1 | ForEach-Object { "      $_" }
}

# ---------------------------------------------------------------- 5. scheduled task
$taskName = "CIMS-Cloudflared-Tunnel"
if ($RegisterTask) {
    $prev = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($prev) { Unregister-ScheduledTask -TaskName $taskName -Confirm:$false }
    $action    = New-ScheduledTaskAction -Execute $cf -Argument ("tunnel --config `"$cfgPath`" run $tunnelId --no-autoupdate")
    $trigger   = New-ScheduledTaskTrigger -AtStartup
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero)
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "Stelarith CIMS public ingress (Cloudflare Tunnel)" | Out-Null
    Start-ScheduledTask -TaskName $taskName
    Ok "scheduled task '$taskName' registered and started"
}

Write-Host ""
Ok "Done. Next:"
Write-Host "    1) set CIMS_BASE_DOMAIN=$Zone in CIMS-backend\.env AND stelarith-website\stelarith\.env"
Write-Host "    2) set CIMS_TRUSTED_PROXIES=127.0.0.1 in CIMS-backend\.env"
Write-Host "    3) restart backend + website"
Write-Host "    4) verify:  curl -i -H `"Host: demo-class.$Zone`" http://127.0.0.1:$ClientPort/api/v1/client/manifest"
Write-Host "       external:  curl -i https://$panelFqdn/admin/login"
